server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: quantity-service
          uri: lb://QUANTITY-SERVICE
          predicates:
            - Path=/api/v1/quantities/**
          filters:
            - AuthenticationFilter